### ISSUE TITLE
StorageAPIのドキュメント内容に異なる説明が記載されている

### ISSUE THREAD

**Issue by Sinoa** [atsumaru/api-references#16]
content/collections/apis/storage.md
に記載されている、サーバーセーブ削除APIの項にて
メソッドはそれらしいAPIが記載されていますが
説明欄が外部リンクを開くAPIのものになっています。

**Comment by atsumalion** [comment]
ご報告ありがとうございます！

https://github.com/atsumaru/api-references/pull/17 にて対応させていただきましたのでご確認ください。
