### ISSUE TITLE
リファレンスの各誤植のご報告

### ISSUE THREAD

**Issue by Sinoa** [atsumaru/api-references#19]
お世話になっております。

いくつかの誤植かと思われる箇所を見つけましたのでまとめてご報告いたします。

**ページ：content/collections/apis/comment.md**

- 箇所１：「設置方法以下にあるAPIタイトル」
コメントAPIの設置リファレンスにもかかわらず
タイトルが「APIを利用したサーバーセーブ機能の利用」となっています。

- 箇所２：「シーン切り替えAPIのメソッドの項目」
ストレージAPIのsetItemsAPIのシグネチャになっています。
おそらく「window.RPGAtsumaru.comment.resetAndChangeScene(sceneName)」かと思われます。

**ページ：content/collections/apis/controller.md**

- 箇所１：「設置方法以下にあるAPIタイトル」
コントローラAPIの設置リファレンスにもかかわらず
タイトルが「APIを利用したサーバーセーブ機能の利用」となっています。

**ページ：content/collections/apis/screenshot.md**

- 箇所１：「設置方法以下にあるAPIタイトル」
スクリーンショットAPIの設置リファレンスにもかかわらず
タイトルが「APIを利用した外部リンク設置方法」となっております。

以上となります。

**Comment by atsumalion** [comment]
https://github.com/atsumaru/api-references/pull/20 にて対応させていただきました！

何度もご指摘いただきありがとうございます！感謝します。
