### ISSUE TITLE
限定公開状態のゲームにて、作者以外からも共有セーブの取得が可能なようです

### ISSUE THREAD

**Issue by ayamada** [atsumaru/api-references#26]
https://github.com/atsumaru/api-references/blob/master/content/collections/apis/shared-save.md#%E5%85%B1%E6%9C%89%E3%82%BB%E3%83%BC%E3%83%96%E3%81%AE%E5%8F%96%E5%BE%97%E6%9D%A1%E4%BB%B6
にて

> 作者以外は公開状態のゲームでのみ共有セーブを取得できます。限定公開・非公開状態のゲームの共有セーブを取得できません。

とありますが、限定公開状態のゲームに対して、作者が、ニコニコアカウントをログアウトした状態でアクセスして、共有セーブの取得ができるようです。
(もしかするとキャッシュが残っている等の要因かもしれませんが)

ただ実際問題として、限定公開状態のゲームで作者以外も共有セーブを取得できないと結局作者以外は動作確認が取れず限定公開にしている意味がなくなるので、この現在の挙動の方が便利だと思われます。

この挙動で問題ないようでしたら、このAPIドキュメントの方を現状の動作に沿うように修正された方がよいのではと思いますが、どうでしょうか？

**Comment by atsumalion** [comment]
こちら、確認したところリファレンスに不備があり、ご指摘の通りの内容が正しい挙動でした(正確には、取得元と同じゲームの共有セーブは、作者でなくても公開状態にかかわらず取得できます)。

リファレンスのほうも https://github.com/atsumaru/api-references/pull/27 にて修正させていただいております。この度はご不便をおかけしまして申し訳ありませんでした。

**Comment by ayamada** [comment]
なるほどです、対応どうもありがとうございました！
