### ISSUE TITLE
Issue および Pull request 作成時のデフォルトメッセージ内のURLが404

### ISSUE THREAD

**Issue by ayamada** [atsumaru/api-references#5]
この `api-references` および `mv-plugins` の github のプロジェクトページにて、新しい Issue や Pull request を作成する際に、デフォルトで含まれているメッセージ内に「ガイドラインのURL」が含まれていますが、このURLが間違っていて、404が出てしまいます…。正しいURLに直してほしいです。

**Comment by atsumalion** [comment]
ご報告ありがとうございます！以下のプルリクエストにて修正いたしましたので、このissueはクローズいたします。

- https://github.com/atsumaru/mv-plugins/pull/2
- https://github.com/atsumaru/api-references/pull/6

**Comment by ayamada** [comment]
確認しました。どうもありがとうございます！
